
trigger: 
 - master

pool:
   vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  inputs:
    version: '1.13.5'
# - task: Go@0
#   inputs:
#     command: 'get'
#     arguments: '-d'
#     workingDirectory: '$(System.DefaultWorkingDirectory)'

- script: go env

- task: Go@0
  inputs:
    command: 'build'
    arguments: 'cmd/loki'
    workingDirectory: '$(Build.SourcesDirectory)'

# - task: CopyFiles@2
#   inputs:
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
# - task: PublishBuildArtifacts@1
#   inputs:
#      artifactName: drop