
trigger: 
 - master

pool:
   vmImage: 'ubuntu-latest'

variables:
  GO_VERSION: 1.14.3

steps: 
- task: GoTool@0
  displayName: go $(GO_VERSION)
  inputs:
    version: $(GO_VERSION)

- task: Go@0
  displayName: go build
  inputs:
    command: 'build'
    arguments: './cmd/loki -o "$(Build.ArtifactStagingDirectory)/loki.exe"'
    workingDirectory: '$(Build.SourcesDirectory)'

- publish: $(Build.ArtifactStagingDirectory)
  artifact: build
