
trigger: 
 - master

pool:
   vmImage: 'ubuntu-latest'

variables:
  GO_VERSION: 1.14.3
  GOOS: windows

steps: 
- task: GoTool@0
  displayName: go $(GO_VERSION)
  inputs:
    version: $(GO_VERSION)

- task: Go@0
  displayName: go build
  inputs:
    command: 'build'
    arguments: '-o "$(Build.ArtifactStagingDirectory)/loki.exe" ./cmd/loki'
    workingDirectory: '$(Build.SourcesDirectory)'

- publish: $(Build.ArtifactStagingDirectory)
  artifact: build
